sudo: required
services:
  - docker
after_success:
  - docker build -t 4111997/spring-boot-nest ./nest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push 4111997/spring-boot-nest